version: "3.1"

services:
  database:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432